### ISSUE TITLE
Create Upcoming Events view (summary)

### ISSUE THREAD

**Issue by lhridley** [savaslabs/autism-case-study#38]
Create a view that lists the title and date for upcoming events, sorted by the event start date in ascending order.

Add an argument that will filter the view (using a contextual filter) by taxonomy term designating the target audience for the event.  If no argument is passed display all upcoming events.

Make this views display a block so it can be placed in the sidebar.

Write your behat tests first, that test for the presence of the view in the sidebar region. Write tests to make sure a user with the various roles (anonymous user, authenticated user, staff, and site administrator) can see the view. As before, you will want to write your tests before you start creating your view.

See page 248 for more details.

**Comment by lrowang** [comment]
**This comment was originally part of a [WIP] PR that I've closed in order to start over**. Replicating the comment here for documentation sake, but hope to resolve these issues today.

I'm having a little difficulty with contextual filters.

I can't figure out how to get the contextual filters to actually work. I did some research and understand the concept, but the filter options/settings I've selected aren't working the way I would have expected. I'm still missing something here.

For example, I tried 2 different contextual filter types `Content: Has taxonomy term ID` and `Content: Visitor Type` (separately and together). And neither really seems to be working. You can see the preview actually works when I don't have a contextual filter selected, but if I put one in (like "Caregivers" or "Teachers") then nothing shows up at all! And those content types do have those terms applied to them.

Would you have time tomorrow to discuss in detail?

**Preview works with no filter**
![cs 38-nofilter](https://cloud.githubusercontent.com/assets/19154706/18535187/cc13a47c-7aa6-11e6-8e0e-7c156c4fa4f8.png)

**Preview doesn't work once filter added**
![cs 38-filterbroke](https://cloud.githubusercontent.com/assets/19154706/18535190/d80959c0-7aa6-11e6-983e-04d23a8568fd.png)
